# syntax=docker/dockerfile:1.5
FROM node:20-alpine

WORKDIR /usr/src/app

COPY frontend/package*.json ./
RUN npm install

COPY frontend ./

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
